import React from "react";
import Link from "next/link";
import Head from "next/head";

const Layout = ({ children, title = "Crypto Tracker" }) => {
  return (
    <div className="layout">
      <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a href=""></a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
