import Head from "next/head";
import styles from "../components/SearchBar/Search.module.css";
import SearchBar from "../components/SearchBar/SearchBar";
import CoinList from "../components/CoinList";
import Layout from "../components/Layout";
import { useState } from "react";
import Link from "next/link";

export default function Home({ filteredCoins }) {
  const [search, setSearch] = useState("");

  const allCoins = filteredCoins.filter((coin) =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e) => {
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };

  return (
    <Layout>
      <Head>
        <title>CrAcker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar
        type="search"
        placeholder="Search here..."
        onChange={handleChange}
      />
      <CoinList filteredCoins={allCoins} />
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const res =
    await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=1h%2C24h%2C7d%2C1y
  `);

  const filteredCoins = await res.json();

  return {
    props: {
      filteredCoins,
    },
  };
};
